apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
  namespace: infrastructure
  labels:
    app: zipkin
    component: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
        component: infrastructure
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:latest
          ports:
            - containerPort: 9411
              name: http
          env:
            # Zipkin storage
            - name: STORAGE_TYPE
              value: "mem"
            # JVM settings
            - name: JAVA_OPTS
              value: "-XX:+UseG1GC -Xms512m -Xmx1g"
            # Self-registration with Eureka (optional for Zipkin)
            - name: EUREKA_SERVICE_URL
              value: "http://eureka-server.infrastructure:8761/eureka/"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
      restartPolicy: Always
