apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prometheus
  namespace: observability

resources:
  - prometheus-config.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml

labels:
  - pairs:
      app: prometheus
      component: observability

namespace: observability

replicas:
  - name: prometheus
    count: 1
