apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-server-config
  namespace: infrastructure
  labels:
    app: eureka-server
    component: infrastructure
data:
  application.yml: |
    server:
      port: 8761
    
    spring:
      application:
        name: eureka-server
      profiles:
        active: docker
    
    eureka:
      instance:
        hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka-server}
        prefer-ip-address: false
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 20
      client:
        register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
        fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
        service-url:
          defaultZone: http://eureka-server:8761/eureka/
      server:
        enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:false}
        eviction-interval-timer-in-ms: 10000
        response-cache-update-interval-ms: 5000
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,env,metrics
      endpoint:
        health:
          show-details: always
    
    logging:
      level:
        com.netflix.eureka: INFO
        com.netflix.discovery: INFO