apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: infrastructure
  labels:
    app: eureka-server
    component: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
        component: infrastructure
    spec:
      containers:
      - name: eureka-server
        image: yahyazakaria123/ecommerce-app-discovery-service:latest
        ports:
        - containerPort: 8761
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
          value: "false"
        - name: EUREKA_CLIENT_FETCH_REGISTRY
          value: "false"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "eureka-server"
        - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
      restartPolicy: Always