apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: infrastructure
  labels:
    app: eureka-server
    component: infrastructure
spec:
  selector:
    app: eureka-server
  ports:
  - name: http
    port: 8761
    targetPort: 8761
    protocol: TCP
  type: ClusterIP