apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: istio-service-mesh-dev
  namespace: istio-system

# Reference the base Istio configuration
resources:
  - ../../../../base/infrastructure/istio
  - istio-gateway-dev.yaml
  - virtual-service-observability.yaml
  - canary-deployment-config.yaml

# Use istio-system namespace
namespace: istio-system

# Add environment-specific labels
labels:
  - pairs:
      environment: dev
      tier: development

# Use development image tags
images:
  - name: istio/pilot
    newTag: 1.20.0
  - name: istio/proxyv2
    newTag: 1.20.0

# Generate additional ConfigMap with dev-specific settings
configMapGenerator:
  - name: istio-dev-config
    literals:
      - PILOT_TRACE_SAMPLING=100
      - PILOT_ENABLE_DEBUG=true
      - ENVIRONMENT=development

# Development-specific patches
patches:
  # Reduce Istio control plane resources for development
  - patch: |-
      apiVersion: install.istio.io/v1alpha1
      kind: IstioOperator
      metadata:
        name: nexus-commerce-istio
        namespace: istio-system
      spec:
        values:
          pilot:
            traceSampling: 100.0
            env:
              PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
              PILOT_TRACE_SAMPLING: 100
              PILOT_ENABLE_DEBUG: true
          global:
            proxy:
              resources:
                requests:
                  cpu: 10m
                  memory: 32Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
        components:
          pilot:
            k8s:
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
          ingressGateways:
            - name: istio-ingressgateway
              enabled: true
              k8s:
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 200m
                    memory: 256Mi
                service:
                  type: NodePort
                  ports:
                    - port: 15021
                      targetPort: 15021
                      name: status-port
                      nodePort: 31021
                      protocol: TCP
                    - port: 80
                      targetPort: 8080
                      name: http2
                      nodePort: 31080
                      protocol: TCP
                    - port: 443
                      targetPort: 8443
                      name: https
                      nodePort: 31443
                      protocol: TCP
          egressGateways:
            - name: istio-egressgateway
              enabled: true
              k8s:
                resources:
                  requests:
                    cpu: 50m
                    memory: 64Mi
                  limits:
                    cpu: 200m
                    memory: 256Mi
    target:
      kind: IstioOperator
      name: nexus-commerce-istio

  # Relaxed security for development
  - patch: |-
      apiVersion: security.istio.io/v1beta1
      kind: PeerAuthentication
      metadata:
        name: default
        namespace: microservices
      spec:
        mtls:
          mode: PERMISSIVE
    target:
      kind: PeerAuthentication
      name: default