apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: observability
  labels:
    app: elasticsearch
    component: observability
    tier: logging
data:
  elasticsearch.yml: |
    cluster.name: "nexus-commerce-logs"
    node.name: "elasticsearch-node-1"
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    
    # Discovery
    discovery.type: single-node
    
    # Security Configuration - FIXED: Properly disabled for development
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.authc.api_key.enabled: false
    
    # Monitoring
    xpack.monitoring.collection.enabled: true
    
    # Index settings
    action.auto_create_index: true
    action.destructive_requires_name: true
    
    # Memory settings
    indices.fielddata.cache.size: 20%
    indices.query.bool.max_clause_count: 10000
    
    # Path settings
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs
    
    # Bootstrap settings
    bootstrap.memory_lock: false
    
    # HTTP settings
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    http.cors.allow-headers: "X-Requested-With,Content-Type,Content-Length,Authorization"
    
    # Logging
    logger.level: INFO
    logger.deprecation.level: WARN
    
    # Additional stability settings
    cluster.routing.allocation.disk.threshold_enabled: false