
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: data
  labels:
    app: kafka
    component: data
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: jmx
      port: 9997
      targetPort: 9997
      protocol: TCP
  type: ClusterIP