
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-storage-pvc
  namespace: data
  labels:
    app: kafka
    component: data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
