apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
    component: microservices
spec:
  selector:
    app: notification-service
  ports:
  - name: http
    port: 8086
    targetPort: 8086
    protocol: TCP
  - name: sse
    port: 8087
    targetPort: 8087
    protocol: TCP
  type: ClusterIP