apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: payment-service-dev
  namespace: microservices

# Reference the base payment-service configuration
resources:
- ../../../../base/microservices/payment-service
- payment-service-ingress.yaml

# Use microservices namespace
namespace: microservices

# Add environment-specific labels
labels:
- pairs:
    environment: dev
    tier: development

# Use development image tag
images:
- name: yahyazakaria123/ecommerce-app-payment-service
  newTag: latest  # You can change to dev-latest when available

# Reduce replicas for dev (save resources)
replicas:
- name: payment-service
  count: 1
  