apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: observability
  labels:
    app: logstash
    component: observability
    tier: logging
spec:
  selector:
    app: logstash
  ports:
    - name: beats
      port: 5044
      targetPort: 5044
      protocol: TCP
    - name: tcp
      port: 5000
      targetPort: 5000
      protocol: TCP
    - name: monitoring
      port: 9600
      targetPort: 9600
      protocol: TCP
  type: ClusterIP
