apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices
  labels:
    app: product-service
    component: microservices
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        component: microservices
        tier: backend
    spec:
      containers:
        - name: product-service
          image: yahyazakaria123/ecommerce-app-product-service:latest
          ports:
            - containerPort: 8081
              name: http
          env:
            - name: JAVA_OPTS
              value: "-Xmx1536m -Xms512m -XX:MaxMetaspaceSize=256m"
            # Application Configuration
            - name: SPRING_PROFILES_ACTIVE
              value: "docker,kafka"
            - name: SPRING_APPLICATION_NAME
              value: "product-service"
            - name: SERVER_PORT
              value: "8081"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/api/products"

            # Eureka Configuration
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server.infrastructure.svc.cluster.local:8761/eureka"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "product-service"

            # Config Server Configuration
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server.infrastructure.svc.cluster.local:8888"

            # PostgreSQL Configuration (Cross-namespace)
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.data.svc.cluster.local:5432/productdb"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: product-service-secrets
                  key: db-password



            # Kafka Configuration (Cross-namespace)
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.data.svc.cluster.local:9092"
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "product-service-group"

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

          # Health Checks - Enhanced like cart service
          livenessProbe:
            httpGet:
              path: /api/products/actuator/health
              port: 8081
            initialDelaySeconds: 180  # Increased from 120
            periodSeconds: 45         # Increased from 30
            timeoutSeconds: 15        # Increased from 10
            failureThreshold: 5       # Increased from 3

          readinessProbe:
            httpGet:
              path: /api/products/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 120  # Increased from 90
            periodSeconds: 15         # Increased from 10
            timeoutSeconds: 10        # Increased from 5
            failureThreshold: 8       # Increased from 5

          startupProbe:
            httpGet:
              path: /api/products/actuator/health
              port: 8081
            initialDelaySeconds: 60   # Increased from 30
            periodSeconds: 15         # Increased from 10
            timeoutSeconds: 10        # Increased from 5
            failureThreshold: 30      # Increased from 20

          volumeMounts:
            - name: config-volume
              mountPath: /app/config
            - name: logs-volume
              mountPath: /app/logs

      volumes:
        - name: config-volume
          configMap:
            name: product-service-config
        - name: logs-volume
          emptyDir: {}

      # InitContainers for proper startup order - Enhanced like cart service
      initContainers:
        # Wait for PostgreSQL
        - name: wait-for-postgres
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for PostgreSQL..."
              until nc -z postgres-service.data.svc.cluster.local 5432; do 
                echo "PostgreSQL not ready, waiting..."
                sleep 3
              done
              echo "PostgreSQL is ready!"

        # Wait for Redis - Added like cart service
        - name: wait-for-redis
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Redis..."
              until nc -z redis-service.data.svc.cluster.local 6379; do 
                echo "Redis not ready, waiting..."
                sleep 3
              done
              echo "Redis is ready!"

        # Wait for Kafka
        - name: wait-for-kafka
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Kafka..."
              until nc -z kafka-service.data.svc.cluster.local 9092; do 
                echo "Kafka not ready, waiting..."
                sleep 3
              done
              echo "Kafka is ready!"

        # Wait for Eureka
        - name: wait-for-eureka
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Eureka..."
              until nc -z eureka-server.infrastructure.svc.cluster.local 8761; do 
                echo "Eureka not ready, waiting..."
                sleep 3
              done
              echo "Eureka is ready!"