apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices
  labels:
    app: product-service
    component: microservices
spec:
  selector:
    app: product-service
  ports:
    - name: http
      port: 8082  # Updated to match the application port
      targetPort: 8082  # Updated to match the container port
      protocol: TCP
  type: ClusterIP