apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: api-gateway-dev
  namespace: infrastructure

# Reference the base api-gateway configuration
resources:
- ../../../../base/infrastructure/api-gateway

# Use infrastructure namespace
namespace: infrastructure

# Add environment-specific labels
labels:
- pairs:
    environment: dev
    tier: development

# Use development image tag
images:
- name: yahyazakaria123/ecommerce-app-api-gateway-service
  newTag: latest

# Reduce replicas for dev (save resources)
replicas:
- name: api-gateway
  count: 1

# Generate additional ConfigMap with dev-specific settings
configMapGenerator:
- name: api-gateway-dev-config
  literals:
  - LOG_LEVEL=DEBUG
  - SPRING_PROFILES_ACTIVE=dev,docker,kafka
  - GATEWAY_TIMEOUT=60s
  - ENABLE_REQUEST_LOGGING=true

# Use new patches syntax instead of deprecated patchesStrategicMerge
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-gateway
    spec:
      template:
        spec:
          containers:
          - name: api-gateway
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev,docker,kafka"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: GATEWAY_REQUEST_LOGGING
              value: "true"
            - name: CORS_CONFIGURATION_ALLOWED_ORIGINS
              value: "http://localhost:3000,http://localhost:8080,http://localhost:3001"
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "250m"
  target:
    kind: Deployment
    name: api-gateway

# Patch the service to use NodePort for easy access in dev
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: api-gateway
    spec:
      type: NodePort
      ports:
      - name: http
        port: 8099
        targetPort: 8099
        nodePort: 30099
  target:
    kind: Service
    name: api-gateway