apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-config
  namespace: infrastructure
  labels:
    app: config-server
    component: infrastructure
data:
  application.yml: |
    server:
      port: 8888
    
    spring:
      application:
        name: config-server
      cloud:
        config:
          server:
            git:
              uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/Saoudyahya/Ecommerce-App-Config-serveur-repo.git}
              clone-on-start: true
              default-label: main
      profiles:
        active: docker
    
    # Eureka client configuration - FIXED URLs
    eureka:
      client:
        serviceUrl:
          defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server.infrastructure.svc.cluster.local:8761/eureka}
        register-with-eureka: true
        fetch-registry: true
        registry-fetch-interval-seconds: 10
        initial-instance-info-replication-interval-seconds: 10
        instance-info-replication-interval-seconds: 10
      instance:
        prefer-ip-address: true
        hostname: ${HOSTNAME:config-server}
        instance-id: ${spring.application.name}:${HOSTNAME:config-server}:${server.port}
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 20
        health-check-url-path: /actuator/health
        status-page-url-path: /actuator/info
    
    # Management endpoints
    management:
      endpoints:
        web:
          exposure:
            include: health,info,refresh,beans,env,metrics
      endpoint:
        health:
          show-details: always
    
    # Logging configuration
    logging:
      level:
        org.springframework.cloud.config: INFO
        org.springframework.cloud.netflix.eureka: DEBUG
        com.netflix.discovery: DEBUG
        org.springframework.web: INFO