apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: infrastructure
  labels:
    app: config-server
    component: infrastructure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
        component: infrastructure
    spec:
      containers:
      - name: config-server
        image: yahyazakaria123/ecommerce-app-config-serveur:latest
        ports:
        - containerPort: 8888
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev,docker"  # Match the current pod environment
        - name: LOG_LEVEL
          value: "DEBUG"  # Add missing LOG_LEVEL
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://eureka-server:8761/eureka"
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: "https://github.com/Saoudyahya/Ecommerce-App-Config-serveur-repo"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # Increased delays to allow proper startup time
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 120  # Increased from 60
          periodSeconds: 30
          timeoutSeconds: 5         # Added timeout
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 60   # Increased from 30
          periodSeconds: 10
          timeoutSeconds: 5         # Added timeout
          failureThreshold: 3
        # Add startup probe for slow-starting applications
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12      # Allow up to 2 minutes for startup
      restartPolicy: Always