apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: infrastructure
  labels:
    app: config-server
    component: infrastructure
spec:
  selector:
    app: config-server
  ports:
  - name: http
    port: 8888
    targetPort: 8888
    protocol: TCP
  type: ClusterIP