apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: elk-stack-dev
  namespace: infrastructure

# Reference the base ELK stack configuration
resources:
  - ../../../../base/infrastructure/elk
  - elk-ingress.yaml

# Use infrastructure namespace
namespace: infrastructure

# Add environment-specific labels
labels:
  - pairs:
      environment: dev
      tier: development

# Use development image tags (keeping stable versions for ELK)
images:
  - name: docker.elastic.co/elasticsearch/elasticsearch
    newTag: 8.11.0
  - name: docker.elastic.co/logstash/logstash
    newTag: 8.11.0
  - name: docker.elastic.co/kibana/kibana
    newTag: 8.11.0

# Reduce replicas for dev (save resources)
replicas:
  - name: elasticsearch
    count: 1
  - name: logstash
    count: 1
  - name: kibana
    count: 1

# Generate additional ConfigMap with dev-specific settings
configMapGenerator:
  - name: elk-dev-config
    literals:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
      - CLUSTER_NAME=nexus-commerce-logs-dev
      - ES_HEAP_SIZE=1g
      - LS_HEAP_SIZE=1g

