apiVersion: v2
name: nexus-database
description: A Helm chart for NexusCommerce Database Stack
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - database
  - mongodb
  - postgresql
  - redis
  - kafka
  - microservices

maintainers:
  - name: NexusCommerce Team
    email: team@nexuscommerce.com

dependencies: []