apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Deployment.yaml
  - Service.yaml
  - ConfigMap.yaml
  - Secret.yaml

# Use modern 'labels' instead of deprecated 'commonLabels'
labels:
  - pairs:
      app: user-service
      component: microservices

namespace: microservices

images:
  - name: yahyazakaria123/ecommerce-app-user-service
    newTag: latest

replicas:
  - name: user-service
    count: 1