apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: user-service
  namespace: microservices

resources:
- Deployment.yaml
- Service.yaml
- ConfigMap.yaml
- Secret.yaml

# Use 'labels' instead of deprecated 'commonLabels'
labels:
- pairs:
    app: user-service
    component: microservices
    version: latest

images:
- name: yahyazakaria123/ecommerce-app-user-service
  newTag: latest

namespace: microservices

replicas:
- name: user-service
  count: 2

configMapGenerator:
- name: user-service-env-config
  literals:
  - SPRING_PROFILES_ACTIVE=docker,kafka
  - LOG_LEVEL=INFO
  - JWT_EXPIRATION=86400000

# Use the new patches syntax instead of deprecated patchesStrategicMerge
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: user-service
    spec:
      template:
        spec:
          containers:
          - name: user-service
            volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
          volumes:
          - name: logs-volume
            emptyDir: {}
  target:
    kind: Deployment
    name: user-service