apiVersion: v1
kind: Service
metadata:
  name: order-postgres-service
  namespace: data
  labels:
    app: order-postgres
    component: data
    service: order-service
    tier: database
spec:
  # Headless service for StatefulSet
  clusterIP: None
  selector:
    app: order-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP