apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/infrastructure/config-server

namespace: infrastructure

labels:
- pairs:
    environment: dev
    tier: development

images:
- name: yahyazakaria123/ecommerce-app-config-serveur
  newTag: latest  # Changed from dev-latest to latest

replicas:
- name: config-server
  count: 1

configMapGenerator:
- name: config-server-dev-config
  literals:
  - LOG_LEVEL=DEBUG
  - SPRING_PROFILES_ACTIVE=dev,docker

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: config-server
    spec:
      template:
        spec:
          containers:
          - name: config-server
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev,docker"
            - name: LOG_LEVEL
              value: "DEBUG"
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "250m"
  target:
    kind: Deployment
    name: config-server
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: config-server
    spec:
      type: NodePort
      ports:
      - name: http
        port: 8888
        targetPort: 8888
        nodePort: 30888
  target:
    kind: Service
    name: config-server