apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-mongodb-config
  namespace: data
  labels:
    app: cart-mongodb
    component: data
    service: cart-service
data:
  database-name: "cartdb"
  mongodb-url: "mongodb://cart-mongodb-headless.data.svc.cluster.local:27017/cartdb"

  # MongoDB configuration file
  mongod.conf: |
    storage:
      dbPath: /data/db
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          cacheSizeGB: 0.5  # 512MB cache
    
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
      logRotate: reopen
    
    net:
      port: 27017
      bindIp: 0.0.0.0
      maxIncomingConnections: 100
    
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
    
    replication:
      replSetName: "cart-replica-set"
    
    # Security settings
    security:
      authorization: enabled
