apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: product-service-dev
  namespace: microservices

# Reference the base product-service configuration
resources:
- ../../../../base/microservices/product-service

# Use microservices namespace
namespace: microservices

# Add environment-specific labels - use 'labels' instead of deprecated 'commonLabels'
labels:
- pairs:
    environment: dev
    tier: development

# Use development image tag
images:
- name: yahyazakaria123/ecommerce-app-product-service
  newTag: latest  # You can change to dev-latest when available

# Reduce replicas for dev (save resources)
replicas:
- name: product-service
  count: 1

# Generate additional ConfigMap with dev-specific settings
configMapGenerator:
- name: product-service-dev-config
  literals:
  - LOG_LEVEL=DEBUG
  - SPRING_PROFILES_ACTIVE=dev,docker,kafka
  - ENABLE_REQUEST_LOGGING=true
  - PRODUCT_CACHE_TTL=1800
  - PRODUCT_PAGINATION_DEFAULT_SIZE=10

# Use the new patches syntax for better compatibility
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: product-service
      namespace: microservices
    spec:
      template:
        spec:
          containers:
          - name: product-service
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev,docker,kafka"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: ENABLE_REQUEST_LOGGING
              value: "true"
            # Dev-specific database configuration
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.data.svc.cluster.local:5432/productdb_dev"
            - name: SPRING_DATA_REDIS_DATABASE
              value: "2"
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "250m"
  target:
    kind: Deployment
    name: product-service

# Patch the service to use NodePort for easy access in dev
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: product-service
      namespace: microservices
    spec:
      type: NodePort
      ports:
      - name: http
        port: 8081
        targetPort: 8081
        nodePort: 30081
  target:
    kind: Service
    name: product-service