apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali
  labels:
    app: kiali
    component: observability
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: [""]
    resources:
      - pods/portforward
    verbs:
      - create
      - get
      - list
      - patch
      - update
  - apiGroups: ["extensions", "apps"]
    resources:
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.istio.io
      - security.istio.io
      - extensions.istio.io
      - telemetry.istio.io
      - install.istio.io
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups: ["apps.openshift.io"]
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["project.openshift.io"]
    resources:
      - projects
    verbs:
      - get
  - apiGroups: ["route.openshift.io"]
    resources:
      - routes
    verbs:
      - get
  - apiGroups: ["iter8.tools"]
    resources:
      - experiments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups: ["authentication.k8s.io"]
    resources:
      - tokenreviews
    verbs:
      - create
