apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali-config
  namespace: observability
  labels:
    app: kiali
    component: observability
data:
  config.yaml: |
    istio_namespace: istio-system
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces:
        - "**"
      namespace: observability
    server:
      port: 20001
      web_root: /kiali
    external_services:
      istio:
        root_namespace: istio-system
        config_map_name: istio
        istio_sidecar_annotation: sidecar.istio.io/status
        url_service_version: http://istiod.istio-system:15014/version
      prometheus:
        url: http://prometheus.observability:9090
      grafana:
        enabled: true
        in_cluster_url: http://grafana.observability:3000
        url: http://grafana.nexus-commerce.local
      tracing:
        enabled: true
        in_cluster_url: http://zipkin-server.infrastructure:9411
        url: http://zipkin.nexus-commerce.local
        use_grpc: false
    api:
      namespaces:
        exclude:
          - istio-operator
          - kube.*
          - openshift.*
          - ibm.*
          - kiali-operator
          - observability
    login_token:
      signing_key: kiali-signing-key
