apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kiali
  namespace: observability

resources:
  - ServiceAccount.yaml
  - ClusterRole.yaml
  - ClusterRoleBinding.yaml
  - ConfigMap.yaml
  - Deployment.yaml
  - Service.yaml

labels:
  - pairs:
      app: kiali
      component: observability
      version: "v1.76"

images:
  - name: quay.io/kiali/kiali
    newTag: v1.76

namespace: observability

replicas:
  - name: kiali
    count: 1