apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: observability
  labels:
    app: kiali
    component: observability
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 20001
      targetPort: api-port
    - name: http-metrics
      protocol: TCP
      port: 9090
      targetPort: http-metrics
  selector:
    app: kiali
