apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: observability
  labels:
    app: kibana
    component: observability
    tier: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        component: observability
        tier: logging
    spec:
      nodeSelector:
        node-role: observability
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          ports:
            - containerPort: 5601
              name: http
          env:
            # FIXED: Cleaned up environment variables for 8.x
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.observability.svc.cluster.local:9200"
            - name: SERVER_NAME
              value: "kibana"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "5601"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              value: "a_very_long_random_key_that_is_at_least_32_characters_long_for_dev_use_only"
            - name: MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
              value: "true"
            - name: LOGGING_ROOT_LEVEL
              value: "info"
            # CRITICAL: Set Node.js memory limit
            - name: NODE_OPTIONS
              value: "--max-old-space-size=1024"
            # FIXED: Remove deprecated timeout configurations
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
            - name: kibana-data
              mountPath: /usr/share/kibana/data
          # FIXED: Improved probe timings for Kibana 8.x
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
              httpHeaders:
                - name: kbn-xsrf
                  value: "true"
            initialDelaySeconds: 300  # Increased - Kibana 8.x takes longer to start
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
              httpHeaders:
                - name: kbn-xsrf
                  value: "true"
            initialDelaySeconds: 180   # Increased
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /api/status
              port: 5601
              httpHeaders:
                - name: kbn-xsrf
                  value: "true"
            initialDelaySeconds: 60
            periodSeconds: 30  # Longer periods for startup
            timeoutSeconds: 15
            failureThreshold: 20      # Allow up to 10 minutes for startup
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
        - name: kibana-data
          emptyDir: {}
      initContainers:
        # IMPROVED: Better Elasticsearch readiness check
        - name: wait-for-elasticsearch
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Elasticsearch to be ready..."
              # First check if Elasticsearch is responding
              until wget -q --spider --timeout=10 http://elasticsearch.observability.svc.cluster.local:9200; do 
                echo "Elasticsearch not responding, waiting 10 seconds..."
                sleep 10
              done
              echo "Elasticsearch is responding, checking cluster health..."
              
              # Wait for Elasticsearch cluster health (yellow is acceptable for single node)
              until wget -q --spider --timeout=30 "http://elasticsearch.observability.svc.cluster.local:9200/_cluster/health?wait_for_status=yellow&timeout=60s"; do 
                echo "Elasticsearch cluster not healthy, waiting 15 seconds..."
                sleep 15
              done
              echo "Elasticsearch cluster is healthy!"
              
              # Additional wait to ensure Elasticsearch is fully initialized
              echo "Waiting additional 30 seconds for Elasticsearch to fully initialize..."
              sleep 30
              echo "Elasticsearch is ready for Kibana!"

        # ADDED: Check for required Elasticsearch indices
        - name: check-elasticsearch-indices
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Checking Elasticsearch indices..."
              # Try to create a test index to ensure Elasticsearch is working
              wget -q --post-data='{"settings":{"number_of_shards":1,"number_of_replicas":0}}' \
                   --header='Content-Type: application/json' \
                   --timeout=10 \
                   http://elasticsearch.observability.svc.cluster.local:9200/test-index || true
              
              # Delete the test index
              wget -q --method=DELETE \
                   --timeout=10 \
                   http://elasticsearch.observability.svc.cluster.local:9200/test-index || true
              
              echo "Elasticsearch index operations test completed!"

      # ADDED: Security context and termination grace period
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      terminationGracePeriodSeconds: 60