apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: observability
  labels:
    app: kibana
    component: observability
    tier: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        component: observability
        tier: logging
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          ports:
            - containerPort: 5601
              name: http
          env:
            # FIXED: Cleaned up environment variables for 8.x
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.observability.svc.cluster.local:9200"
            - name: SERVER_NAME
              value: "kibana"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "5601"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
            - name: MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
              value: "true"
            - name: LOGGING_ROOT_LEVEL
              value: "info"
            # FIXED: Remove problematic timeout and auth configurations
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
            - name: kibana-data
              mountPath: /usr/share/kibana/data
          # FIXED: More realistic probe timings for Kibana 8.x
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
              httpHeaders:
                - name: kbn-xsrf
                  value: "true"
            initialDelaySeconds: 180  # Increased - Kibana 8.x takes longer to start
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
              httpHeaders:
                - name: kbn-xsrf
                  value: "true"
            initialDelaySeconds: 120   # Increased
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /api/status
              port: 5601
              httpHeaders:
                - name: kbn-xsrf
                  value: "true"
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 30      # Allow up to 7.5 minutes for startup
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
        - name: kibana-data
          emptyDir: {}
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Elasticsearch to be ready..."
              # Wait for Elasticsearch cluster health
              until wget -q --spider --timeout=10 http://elasticsearch.observability.svc.cluster.local:9200/_cluster/health?wait_for_status=yellow&timeout=60s; do 
                echo "Elasticsearch not ready, waiting 15 seconds..."
                sleep 15
              done
              echo "Elasticsearch is ready!"
              # Additional wait to ensure Elasticsearch is fully initialized
              echo "Waiting additional 60 seconds for Elasticsearch to fully initialize..."
              sleep 60