apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-service-config
  namespace: microservices
  labels:
    app: shipping-service
    component: microservices
data:
  # Server settings
  SERVER_PORT: "8085"
  ENVIRONMENT: "development"

  # Config Server settings
  CONFIG_SERVER_URL: "http://config-server.infrastructure.svc.cluster.local:8888"
  CONFIG_PROFILE: "development"
  CONFIG_LABEL: "main"

  # Database settings (fallback if Config Server is unavailable)
  DB_HOST: "shipping-postgres-service.data.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "shippingdb"

  # Enhanced features
  ENABLE_GPS_TRACKING: "true"
  ENABLE_REAL_TIME_LOCATION: "true"
  DEFAULT_ORIGIN_COMPANY: "Shipping Company"
  DEFAULT_ORIGIN_ADDRESS: "123 Warehouse St"
  DEFAULT_ORIGIN_CITY: "Distribution City"
  DEFAULT_ORIGIN_STATE: "DC"
  DEFAULT_ORIGIN_POSTAL: "12345"
  DEFAULT_ORIGIN_COUNTRY: "USA"

  # Eureka settings
  EUREKA_PREFER_IP_ADDRESS: "true"
  EUREKA_INSTANCE_HOSTNAME: "shipping-service"
  EUREKA_INSTANCE_ID: "shipping-service:8085"
  EUREKA_URL: "http://eureka-server.infrastructure.svc.cluster.local:8761/eureka"

  # Kafka settings - Basic
  KAFKA_BROKERS: "kafka-service.data.svc.cluster.local:9092"
  KAFKA_CONSUMER_GROUP: "shipping-service-group"
  KAFKA_ENABLE_CONSUMER: "true"

  # Kafka settings - Shipping topics
  KAFKA_SHIPPING_CREATED_TOPIC: "shipping-created"
  KAFKA_SHIPPING_UPDATED_TOPIC: "shipping-updated"
  KAFKA_SHIPPING_STATUS_CHANGED_TOPIC: "shipping-status-changed"
  KAFKA_SHIPPING_DELETED_TOPIC: "shipping-deleted"
  KAFKA_SHIPPING_ORDER_UPDATE_TOPIC: "shipping-update"

  # Kafka settings - Tracking topics
  KAFKA_TRACKING_CREATED_TOPIC: "tracking-created"
  KAFKA_TRACKING_UPDATED_TOPIC: "tracking-updated"
  KAFKA_TRACKING_DELETED_TOPIC: "tracking-deleted"

  # ELK Stack Configuration
  ENABLE_ELK_LOGGING: "true"
  ENABLE_KAFKA_LOGGING: "true"
  ELK_KAFKA_TOPIC: "app-logs"

  # Elasticsearch Configuration
  ELASTICSEARCH_URL: "http://elasticsearch-service.data.svc.cluster.local:9200"
  ELASTICSEARCH_USERNAME: ""
  ELASTICSEARCH_PASSWORD: ""

  # Logstash Configuration
  LOGSTASH_HOST: "logstash-service.data.svc.cluster.local"
  LOGSTASH_PORT: "5044"

  # Kibana Configuration
  KIBANA_URL: "http://kibana-service.data.svc.cluster.local:5601"

  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"

  # Service Information
  SERVICE_VERSION: "2.0.0"
  SERVICE_NAME: "shipping-service"

  # Performance Monitoring
  ENABLE_METRICS: "true"
  METRICS_PORT: "9090"

  # Service mode configuration
  USE_SHIPPING_ONLY: "false"
  USE_TRACKING_ONLY: "false"

  # Go Runtime settings
  GOOS: "linux"
  GOARCH: "amd64"
  GIN_MODE: "release"

  # Application name for Eureka
  APP_NAME: "SHIPPING-SERVICE"
  HOST_NAME: "shipping-service"