apiVersion: v1
kind: Secret
metadata:
  name: shipping-service-secrets
  namespace: microservices
  labels:
    app: shipping-service
    component: microservices
type: Opaque
data:
  # Database credentials (base64 encoded)
  db-username: c2hpcHBpbmdzZXJ2aWNl  # shippingservice
  db-password: c2hpcHBpbmdzZXJ2aWNlMTIz  # shippingservice123

  # Database connection details
  db-host: c2hpcHBpbmctcG9zdGdyZXMtc2VydmljZS5kYXRhLnN2Yy5jbHVzdGVyLmxvY2Fs  # shipping-postgres-service.data.svc.cluster.local
  db-port: NTQzMg==  # 5432
  db-name: c2hpcHBpbmdkYg==  # shippingdb

  # JWT Configuration (base64 encoded)
  jwt-secret: c2hpcHBpbmctand0LXNlY3JldC1rZXktZm9yLWF1dGhlbnRpY2F0aW9uLWFuZC1hdXRob3JpemF0aW9uLTIwMjQ=  # shipping-jwt-secret-key-for-authentication-and-authorization-2024

  # Encryption keys (base64 encoded)
  encryption-key: c2hpcHBpbmctZW5jcnlwdGlvbi1rZXktZm9yLXNlbnNpdGl2ZS1kYXRhLWVuY3J5cHRpb24=  # shipping-encryption-key-for-sensitive-data-encryption

  # API Keys for external services (base64 encoded)
  # GPS Tracking Service API Key
  gps-api-key: Z3BzLXRyYWNraW5nLWFwaS1rZXktZm9yLXJlYWwtdGltZS1sb2NhdGlvbi11cGRhdGVz  # gps-tracking-api-key-for-real-time-location-updates

  # Geocoding Service API Key (for address resolution)
  geocoding-api-key: Z2VvY29kaW5nLWFwaS1rZXktZm9yLWFkZHJlc3MtcmVzb2x1dGlvbi1zZXJ2aWNl  # geocoding-api-key-for-address-resolution-service

  # Shipping Providers API Keys
  # UPS API Credentials
  ups-api-key: dXBzLWFwaS1rZXktZm9yLXNoaXBwaW5nLWludGVncmF0aW9u  # ups-api-key-for-shipping-integration
  ups-username: dXBzLXVzZXJuYW1l  # ups-username
  ups-password: dXBzLXBhc3N3b3Jk  # ups-password

  # FedEx API Credentials
  fedex-api-key: ZmVkZXgtYXBpLWtleS1mb3Itc2hpcHBpbmctaW50ZWdyYXRpb24=  # fedex-api-key-for-shipping-integration
  fedex-secret: ZmVkZXgtc2VjcmV0LWtleQ==  # fedex-secret-key

  # DHL API Credentials
  dhl-api-key: ZGhsLWFwaS1rZXktZm9yLXNoaXBwaW5nLWludGVncmF0aW9u  # dhl-api-key-for-shipping-integration
  dhl-secret: ZGhsLXNlY3JldC1rZXk=  # dhl-secret-key

  # Notification Service Credentials
  email-service-api-key: ZW1haWwtc2VydmljZS1hcGkta2V5LWZvci1ub3RpZmljYXRpb25z  # email-service-api-key-for-notifications
  sms-service-api-key: c21zLXNlcnZpY2UtYXBpLWtleS1mb3Itbm90aWZpY2F0aW9ucw==  # sms-service-api-key-for-notifications

  # Webhook secrets for external integrations
  webhook-secret: c2hpcHBpbmctd2ViaG9vay1zZWNyZXQtZm9yLXZlcmlmaWNhdGlvbg==  # shipping-webhook-secret-for-verification

  # Admin API Key for internal operations
  admin-api-key: c2hpcHBpbmctYWRtaW4tYXBpLWtleS1mb3ItaW50ZXJuYWwtb3BlcmF0aW9ucw==  # shipping-admin-api-key-for-internal-operations

  # Audit and Compliance
  audit-encryption-key: YXVkaXQtZW5jcnlwdGlvbi1rZXktZm9yLXNoaXBwaW5nLWNvbXBsaWFuY2U=  # audit-encryption-key-for-shipping-compliance

  # Cache and Session Management
  redis-password: ""  # Leave empty if Redis doesn't require auth
  session-secret: c2hpcHBpbmctc2Vzc2lvbi1zZWNyZXQtZm9yLXNlY3VyaXR5  # shipping-session-secret-for-security

  # SSL/TLS Certificates (if needed for external API calls)
  client-cert: ""  # Client certificate for mTLS (base64 encoded PEM)
  client-key: ""   # Client private key for mTLS (base64 encoded PEM)
  ca-cert: ""      # CA certificate for verifying external services (base64 encoded PEM)

  # Environment-specific override keys
  dev-override-key: ZGV2LW92ZXJyaWRlLWtleS1mb3Itc2hpcHBpbmctZGV2ZWxvcG1lbnQ=  # dev-override-key-for-shipping-development

  # Backup and Recovery
  backup-encryption-key: YmFja3VwLWVuY3J5cHRpb24ta2V5LWZvci1zaGlwcGluZy1kYXRhYmFzZQ==  # backup-encryption-key-for-shipping-database

  # External Service Integration Tokens
  order-service-token: b3JkZXItc2VydmljZS10b2tlbi1mb3Itc2hpcHBpbmctaW50ZWdyYXRpb24=  # order-service-token-for-shipping-integration
  inventory-service-token: aW52ZW50b3J5LXNlcnZpY2UtdG9rZW4tZm9yLXNoaXBwaW5nLWludGVncmF0aW9u  # inventory-service-token-for-shipping-integration

  # Monitoring and Observability
  prometheus-auth-token: cHJvbWV0aGV1cy1hdXRoLXRva2VuLWZvci1zaGlwcGluZy1tZXRyaWNz  # prometheus-auth-token-for-shipping-metrics
  jaeger-auth-token: amFlZ2VyLWF1dGgtdG9rZW4tZm9yLXNoaXBwaW5nLXRyYWNpbmc=  # jaeger-auth-token-for-shipping-tracing