apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: microservices
  labels:
    app: shipping-service
    component: microservices
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: shipping-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
  type: ClusterIP