apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: microservices
  labels:
    app: shipping-service
    component: microservices
  annotations:
    # Service annotations for monitoring and discovery
    prometheus.io/scrape: "true"
    prometheus.io/port: "8082"
    prometheus.io/path: "/metrics"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
spec:
  selector:
    app: shipping-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
  # Session affinity for stateful operations
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300  # 5 minutes