# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

# resources:
# - config-server
# - eureka-server

# commonLabels:
#   environment: dev
#   managed-by: argocd

# namespace: dev-infrastructure

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-infrastructure

# Base resources
resources:
- ../../../base/infrastructure/namespace.yaml
- config-server
- api-gateway

# Target namespace
namespace: infrastructure

# Common labels for dev environment
commonLabels:
  environment: dev
  layer: infrastructure
  managed-by: argocd

# Development image tags
images:
- name: yahyazakaria123/ecommerce-app-config-serveur
  newTag: dev-latest
- name: yahyazakaria123/ecommerce-app-api-gateway-service
  newTag: dev-latest

# Reduce replicas for dev (save resources)
replicas:
- name: config-server
  count: 1
- name: api-gateway
  count: 1

# Dev-specific ConfigMap
configMapGenerator:
- name: dev-environment-config
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=DEBUG
  - SPRING_PROFILES_ACTIVE=dev,docker,kafka
  - REDIS_HOST=redis-service.data.svc.cluster.local
  - KAFKA_BOOTSTRAP_SERVERS=kafka-service.data.svc.cluster.local:9092

# Patches for development environment
patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: config-server
  spec:
    template:
      spec:
        containers:
        - name: config-server
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev,docker"
          - name: LOG_LEVEL
            value: "DEBUG"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api-gateway
  spec:
    template:
      spec:
        containers:
        - name: api-gateway
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "dev,docker,kafka"
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: SPRING_DATA_REDIS_HOST
            value: "redis-service.data.svc.cluster.local"
          - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
            value: "kafka-service.data.svc.cluster.local:9092"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "250m"

# NodePort services for dev access
patchesJson6902:
- target:
    group: ""
    version: v1
    kind: Service
    name: config-server
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30888
- target:
    group: ""
    version: v1
    kind: Service
    name: api-gateway
  patch: |-
    - op: replace
      path: /spec/type
      value: NodePort
    - op: add
      path: /spec/ports/0/nodePort
      value: 30099