apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: infrastructure
  labels:
    app: logstash
    component: infrastructure
    tier: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
        component: infrastructure
        tier: logging
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.11.0
          ports:
            - containerPort: 5044
              name: beats
            - containerPort: 5000
              name: tcp
            - containerPort: 9600
              name: monitoring
          env:
            - name: LS_JAVA_OPTS
              value: "-Xmx1g -Xms1g"
            - name: XPACK_MONITORING_ENABLED
              value: "false"
            - name: XPACK_MONITORING_ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.infrastructure.svc.cluster.local:9200"
          resources:
            requests:
              memory: "1.5Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-pipeline
              mountPath: /usr/share/logstash/pipeline/logstash.conf
              subPath: logstash.conf
          livenessProbe:
            httpGet:
              path: /
              port: 9600
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9600
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 9600
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 20
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
        - name: logstash-pipeline
          configMap:
            name: logstash-pipeline
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Elasticsearch..."
              until nc -z elasticsearch.infrastructure.svc.cluster.local 9200; do 
                echo "Elasticsearch not ready, waiting..."
                sleep 10
              done
              echo "Elasticsearch is ready!"
        - name: wait-for-kafka
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Kafka..."
              until nc -z kafka-service.data.svc.cluster.local 9092; do 
                echo "Kafka not ready, waiting..."
                sleep 10
              done
              echo "Kafka is ready!"