apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ingress-nginx
  namespace: ingress-nginx

resources:
- ServiceAccount.yaml
- Deployment.yaml
- Service.yaml

# Use new labels syntax instead of deprecated commonLabels
labels:
- pairs:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: v1.8.1

images:
- name: registry.k8s.io/ingress-nginx/controller
  newTag: v1.8.1

namespace: ingress-nginx

replicas:
- name: simple-ingress-controller
  count: 2

configMapGenerator:
- name: nginx-custom-config
  literals:
  - custom-http-errors=404,503
  - enable-modsecurity=false
  - enable-owasp-modsecurity-crs=false