# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: nginx-ingress-role
#   namespace: ingress-nginx
#   labels:
#     app.kubernetes.io/name: ingress-nginx
#     app.kubernetes.io/part-of: ingress-nginx
# rules:
#   - apiGroups:
#       - ""
#     resources:
#       - configmaps
#       - pods
#       - secrets
#       - endpoints
#     verbs:
#       - get
#       - list
#       - watch
#   - apiGroups:
#       - ""
#     resources:
#       - services
#     verbs:
#       - get
#       - list
#       - watch
#   - apiGroups:
#       - networking.k8s.io
#     resources:
#       - ingresses
#     verbs:
#       - get
#       - list
#       - watch
#   - apiGroups:
#       - networking.k8s.io
#     resources:
#       - ingresses/status
#     verbs:
#       - update
#   - apiGroups:
#       - networking.k8s.io
#     resources:
#       - ingressclasses
#     verbs:
#       - get
#       - list
#       - watch
#   - apiGroups:
#       - ""
#     resources:
#       - configmaps
#     resourceNames:
#       - ingress-controller-leader
#     verbs:
#       - get
#       - update
#   - apiGroups:
#       - ""
#     resources:
#       - configmaps
#     verbs:
#       - create
#   - apiGroups:
#       - ""
#     resources:
#       - events
#     verbs:
#       - create
#       - patch
