apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include the individual service overlays
resources:
    - elk
    - Kiali  # FIXED: Changed from 'kiali' to 'Kiali' to match directory name

# Use 'labels' instead of deprecated 'commonLabels'
labels:
    - pairs:
          environment: dev
          managed-by: argocd
          platform: nexus-commerce

namespace: observability
