apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grafana
  namespace: observability

resources:
  - grafana-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  -

labels:
  - pairs:
      app: grafana
      component: observability

namespace: observability

replicas:
  - name: grafana
    count: 1