apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: data
  labels:
    app: kafka-ui
    component: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
        component: data
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "nexus-commerce-kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-service:9092"
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: "zookeeper-service:2181"
            - name: KAFKA_CLUSTERS_0_READONLY
              value: "false"
            - name: KAFKA_CLUSTERS_0_METRICS_PORT
              value: "9997"
            - name: KAFKA_CLUSTERS_0_METRICS_TYPE
              value: "JMX"
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: "/"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: LOGGING_LEVEL_COM_PROVECTUS
              value: "INFO"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: kafka-ui-config
              mountPath: /app/config.yml
              subPath: config.yml
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12
      volumes:
        - name: kafka-ui-config
          configMap:
            name: kafka-ui-config
