apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
  namespace: data
  labels:
    app: kafka-ui
    component: data
spec:
  selector:
    app: kafka-ui
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP