apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: observability-stack
  namespace: observability

resources:
  - namespace.yaml
  - elk
  - kiali

labels:
  - pairs:
      component: observability
      managed-by: argocd
      platform: nexus-commerce

namespace: observability

# Common configurations for the entire observability stack
configMapGenerator:
  - name: observability-common-config
    literals:
      - CLUSTER_NAME=nexus-commerce
      - ENVIRONMENT=base
      - LOG_LEVEL=INFO