apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ZakariaRek/gitops-repo_ArgoCD
    targetRevision: HEAD
    path: environments/dev/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/nexus-commerce-gitops.git
    targetRevision: HEAD
    path: base/infrastructure/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true