apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-istio-service-mesh
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy Istio first
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ZakariaRek/gitops-repo_ArgoCD
    targetRevision: HEAD
    path: environments/dev/infrastructure/istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Required for Istio CRDs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: install.istio.io
      kind: IstioOperator
      jsonPointers:
        - /spec/revision
        - /status