apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/microservices/user-service
#  - user-service-ingress.yaml

namespace: microservices

commonLabels:
  app: user-service
  component: microservices
  environment: dev

images:
  - name: yahyazakaria123/ecommerce-app-user-service
    newTag: latest

replicas:
  - name: user-service
    count: 1

# Use modern patches syntax instead of deprecated patchesStrategicMerge
patches:
  # Deployment patches
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: user-service
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          deployment.kubernetes.io/revision: "1"
          app.kubernetes.io/managed-by: "kustomize"
      - op: add
        path: /spec/template/metadata/annotations
        value:
          config.linkerd.io/skip-inbound-ports: "8081"
          config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "0"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRING_PROFILES_ACTIVE
          value: "dev,docker,kafka"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRING_CLOUD_CONFIG_FAIL_FAST
          value: "false"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRING_CLOUD_CONFIG_RETRY_ENABLED
          value: "true"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"

  # Service patch to use NodePort for dev
  - target:
      version: v1
      kind: Service
      name: user-service
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30081

# Generate additional config for dev
configMapGenerator:
  - name: user-service-dev-config
    literals:
      - SPRING_PROFILES_ACTIVE=dev,docker,kafka
      - LOG_LEVEL=DEBUG
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server.infrastructure.svc.cluster.local:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server.infrastructure.svc.cluster.local:8888