apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/microservices/user-service

namespace: microservices

# Use modern 'labels' instead of deprecated 'commonLabels'
labels:
  - pairs:
      app: user-service
      component: microservices
      environment: dev

images:
  - name: yahyazakaria123/ecommerce-app-user-service
    newTag: latest

replicas:
  - name: user-service
    count: 1

# Generate additional config for dev
configMapGenerator:
  - name: user-service-dev-config
    literals:
      - SPRING_PROFILES_ACTIVE=dev,docker,kafka
      - LOG_LEVEL=DEBUG
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server.infrastructure.svc.cluster.local:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://config-server.infrastructure.svc.cluster.local:8888