apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/microservices/user-service

namespace: microservices

labels:
- pairs:
    environment: dev

images:
- name: yahyazakaria123/ecommerce-app-user-service
  newTag: latest

replicas:
- name: user-service
  count: 1