apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: enhanced-metrics-collection
  namespace: istio-system
spec:
  metrics:
    - providers:
        - name: prometheus
    - overrides:
        - match:
            metric: REQUEST_COUNT
          tagOverrides:
            destination_service_name:
              value: "{{.destination_workload}}"
            source_app:
              value: "{{.source_app}}"
            request_protocol:
              value: "{{.request_protocol}}"
            response_code:
              value: "{{.response_code}}"
        - match:
            metric: REQUEST_DURATION
          tagOverrides:
            destination_service_name:
              value: "{{.destination_workload}}"
            source_app:
              value: "{{.source_app}}"
        - match:
            metric: TCP_OPENED_CONNECTIONS
          tagOverrides:
            destination_service_name:
              value: "{{.destination_workload}}"
