apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: nexus-commerce-istio
  namespace: istio-system
spec:
  # Istio configuration for microservices platform
  values:
    pilot:
      traceSampling: 100.0  # Full tracing for dev
    global:
      meshID: nexus-commerce
      multiCluster:
        clusterName: nexus-commerce-cluster
      network: nexus-commerce-network
      proxy:
        # Configure sidecar resources
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
      # Istio telemetry integration
      tracer:
        zipkin:
          address: zipkin-server.infrastructure:9411

  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        # Pilot configuration
        env:
          - name: PILOT_TRACE_SAMPLING
            value: "100"
          - name: PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION
            value: true

    # Istio Ingress Gateway
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          service:
            type: LoadBalancer
            ports:
              - port: 15021
                targetPort: 15021
                name: status-port
                protocol: TCP
              - port: 80
                targetPort: 8080
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 8443
                name: https
                protocol: TCP
              - port: 15443
                targetPort: 15443
                name: tls
                protocol: TCP

    # Egress Gateway for external services
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi