# base/infrastructure/istio/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: istio-service-mesh
  namespace: istio-system

resources:
  - namespace.yaml
  - gateway.yaml
  - virtual-service-api-gateway.yaml
  - destination-rules.yaml
  - service-entries.yaml
  - peer-authentication.yaml
  - authorization-policy.yaml
  - custom-metrics-telemetry.yaml
  - access-logging-telemetry.yaml

labels:
  - pairs:
      component: istio-service-mesh
      managed-by: argocd
      platform: nexus-commerce

namespace: istio-system

# Istio operator and control plane images
images:
  - name: istio/pilot
    newTag: 1.20.0
  - name: istio/proxyv2
    newTag: 1.20.0

# Generate ConfigMap with enhanced observability settings
configMapGenerator:
  - name: istio-observability-config
    literals:
      - PROMETHEUS_NAMESPACE=observability
      - GRAFANA_NAMESPACE=observability
      - KIALI_NAMESPACE=observability
      - METRICS_COLLECTION_INTERVAL=15s
      - ACCESS_LOG_FORMAT=json
      - TRACING_SAMPLING_RATE=1.0/installation.yaml should be moved to argocd/applications/istio-installation.yaml