apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: infrastructure
  labels:
    app: api-gateway
    component: infrastructure
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 8099
    targetPort: 8099
    protocol: TCP
  type: ClusterIP