apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: infrastructure
  labels:
    app: kibana
    component: infrastructure
    tier: logging
data:
  kibana.yml: |
    # Server configuration
    server.name: "kibana"
    server.host: "0.0.0.0"
    server.port: 5601
    # FIX: This cannot be empty in Kibana 8.x
    server.publicBaseUrl: "http://kibana.infrastructure.svc.cluster.local:5601"
    
    # Elasticsearch configuration
    elasticsearch.hosts: ["http://elasticsearch.infrastructure.svc.cluster.local:9200"]
    elasticsearch.username: ""
    elasticsearch.password: ""
    elasticsearch.requestTimeout: 30000
    elasticsearch.shardTimeout: 30000
    elasticsearch.pingTimeout: 1500
    elasticsearch.startupTimeout: 5000
    
    # Security configuration (disabled for development)
    xpack.security.enabled: false
    xpack.security.encryptionKey: "something_at_least_32_characters_long"
    xpack.security.sessionTimeout: 600000
    
    # Monitoring configuration
    xpack.monitoring.ui.container.elasticsearch.enabled: true
    xpack.monitoring.kibana.collection.enabled: false
    
    # Features configuration
    xpack.canvas.enabled: true
    xpack.infra.enabled: true
    xpack.apm.enabled: false
    xpack.uptime.enabled: false
    xpack.ml.enabled: false
    
    # Logging configuration
    logging.root.level: info
    logging.appenders.default:
      type: console
      layout:
        type: json
    
    # UI configuration
    i18n.locale: "en"
    
    # Index patterns
    kibana.index: ".kibana"
    kibana.defaultAppId: "discover"
    
    # Save objects
    savedObjects.maxImportPayloadBytes: 26214400
    savedObjects.maxImportExportSize: 10000
