apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: infrastructure
  labels:
    app: kibana
    component: infrastructure
    tier: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        component: infrastructure
        tier: logging
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.11.0
          ports:
            - containerPort: 5601
              name: http
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.infrastructure.svc.cluster.local:9200"
            - name: SERVER_NAME
              value: "kibana"
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "5601"
            - name: ELASTICSEARCH_USERNAME
              value: ""
            - name: ELASTICSEARCH_PASSWORD
              value: ""
            - name: XPACK_SECURITY_ENABLED
              value: "false"
            - name: XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED
              value: "true"
            - name: LOGGING_ROOT_LEVEL
              value: "info"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
          # FIXED: Much more generous probe timings for Kibana 8.x
          livenessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 300  # Wait 5 minutes before first check
            periodSeconds: 60         # Check every minute
            timeoutSeconds: 30        # Allow 30 seconds for response
            failureThreshold: 5       # Allow 5 failures before restart
          readinessProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 180  # Wait 3 minutes before first check
            periodSeconds: 30         # Check every 30 seconds
            timeoutSeconds: 15        # Allow 15 seconds for response
            failureThreshold: 5       # Allow 5 failures before marking unready
          startupProbe:
            httpGet:
              path: /api/status
              port: 5601
            initialDelaySeconds: 60   # Wait 1 minute before starting checks
            periodSeconds: 30         # Check every 30 seconds
            timeoutSeconds: 15        # Allow 15 seconds for response
            failureThreshold: 40      # Allow up to 20 minutes total startup time (40 * 30s)
      volumes:
        - name: kibana-config
          configMap:
            name: kibana-config
      initContainers:
        - name: wait-for-elasticsearch
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for Elasticsearch to be ready..."
              until wget -q --spider http://elasticsearch.infrastructure.svc.cluster.local:9200/_cluster/health; do 
                echo "Elasticsearch not ready, waiting..."
                sleep 15
              done
              echo "Elasticsearch is ready!"