apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: infrastructure
  labels:
    app: kibana
    component: infrastructure
    tier: logging
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      protocol: TCP
  type: ClusterIP
