# environments/dev/observability/grafana/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: grafana-dev
  namespace: observability

# Reference the base Grafana configuration
resources:
  - ../../../../base/observability/grafana

# Use observability namespace
namespace: observability

# Add environment-specific labels
labels:
  - pairs:
      environment: dev
      tier: development

# Use stable Grafana image
images:
  - name: grafana/grafana
    newTag: 10.0.0

# Single replica for dev
replicas:
  - name: grafana
    count: 1

# Generate additional ConfigMap with dev-specific settings
configMapGenerator:
  - name: grafana-dev-config
    literals:
      - ENVIRONMENT=development
      - GF_LOG_LEVEL=info
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false

# Development-specific patches
patches:
  # Patch Grafana deployment for dev environment
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: grafana
        namespace: observability
      spec:
        template:
          spec:
            nodeSelector:
              node-role: observability
            containers:
              - name: grafana
                env:
                  - name: GF_SECURITY_ADMIN_PASSWORD
                    value: "admin123"  # Dev password
                  - name: GF_USERS_ALLOW_SIGN_UP
                    value: "false"
                  - name: GF_SERVER_DOMAIN
                    value: "grafana.nexus-commerce.local"
                  - name: GF_SERVER_ROOT_URL
                    value: "http://grafana.nexus-commerce.local"
                  - name: GF_LOG_LEVEL
                    value: "info"
                  - name: GF_SECURITY_ALLOW_EMBEDDING
                    value: "true"
                  - name: GF_AUTH_ANONYMOUS_ENABLED
                    value: "true"
                  - name: GF_AUTH_ANONYMOUS_ORG_ROLE
                    value: "Viewer"
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "50m"
                  limits:
                    memory: "256Mi"
                    cpu: "200m"
    target:
      kind: Deployment
      name: grafana

  # Patch ConfigMap for dev-specific Grafana config
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: grafana-config
        namespace: observability
      data:
        grafana.ini: |
          [analytics]
          check_for_updates = true
          
          [grafana_net]
          url = https://grafana.net
          
          [log]
          mode = console
          level = info
          
          [paths]
          data = /var/lib/grafana/data
          logs = /var/log/grafana
          plugins = /var/lib/grafana/plugins
          provisioning = /etc/grafana/provisioning
          
          [server]
          domain = grafana.nexus-commerce.local
          root_url = http://grafana.nexus-commerce.local
          
          [security]
          allow_embedding = true
          
          [auth.anonymous]
          enabled = true
          org_role = Viewer
          
          [users]
          allow_sign_up = false

        datasources.yaml: |
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus.observability.svc.cluster.local:9090
              isDefault: true
              editable: true
            - name: Elasticsearch
              type: elasticsearch
              access: proxy
              url: http://elasticsearch.observability.svc.cluster.local:9200
              database: "microservices-logs-*"
              timeField: "@timestamp"
              version: 8
              editable: true

        dashboards.yaml: |
          apiVersion: 1
          providers:
            - name: 'istio'
              orgId: 1
              folder: 'Istio Service Mesh'
              type: file
              disableDeletion: false
              updateIntervalSeconds: 10
              allowUiUpdates: true
              options:
                path: /var/lib/grafana/dashboards
            - name: 'microservices'
              orgId: 1
              folder: 'Microservices'
              type: file
              disableDeletion: false
              updateIntervalSeconds: 10
              allowUiUpdates: true
              options:
                path: /var/lib/grafana/dashboards
    target:
      kind: ConfigMap
      name: grafana-config

  # Patch service to use NodePort for dev access
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: grafana
        namespace: observability
      spec:
        type: NodePort
        ports:
          - name: grafana
            port: 3000
            targetPort: grafana
            nodePort: 30300
            protocol: TCP
    target:
      kind: Service
      name: grafana