apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include the individual service overlays
resources:
- user-service
- product-service
- notification-service
- payment-service
- cart-service
- loyalty-service
- order-service

# Use 'labels' instead of deprecated 'commonLabels'
labels:
- pairs:
    environment: dev
    managed-by: argocd
    platform: nexus-commerce

namespace: microservices