apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include the individual service overlays
resources:
- user-service
- product-service
- notification-service

# Use 'labels' instead of deprecated 'commonLabels'
labels:
- pairs:
    environment: dev
    managed-by: argocd

namespace: microservices