apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ingress-nginx-dev
  namespace: ingress-nginx

# Reference the simple-ingress instead of the commented-out base ingress-nginx
resources:
- ../../../../base/infrastructure/ingress-nginx
- api-gateway-ingress.yaml
- health-ingress.yaml

# Use ingress-nginx namespace
namespace: ingress-nginx

# Add environment-specific labels using new syntax
labels:
- pairs:
    environment: dev
    tier: development

# Use stable image tags for dev
images:
- name: registry.k8s.io/ingress-nginx/controller
  newTag: v1.8.1

# Single replica for dev (save resources)
replicas:
- name: simple-ingress-controller
  count: 1

# Generate additional ConfigMap with dev-specific settings
configMapGenerator:
- name: nginx-dev-config
  literals:
  - enable-access-log=true
  - log-format-escape-json=true
  - enable-real-ip=true

# Use new patches syntax instead of deprecated ones
patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: simple-ingress-controller
    spec:
      template:
        spec:
          nodeSelector:
            node-role: infrastructure
          containers:
          - name: nginx-ingress-controller
            args:
            - /nginx-ingress-controller
            - --ingress-class=nginx
            - --watch-namespace=$(POD_NAMESPACE)
            - --v=2
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 256Mi
  target:
    kind: Deployment
    name: simple-ingress-controller

# Patch the service to use NodePort for dev access
- patch: |-
    apiVersion: v1
    kind: Service
    metadata:
      name: simple-ingress-controller
    spec:
      type: NodePort
      ports:
      - name: http
        port: 80
        targetPort: 80
        nodePort: 30080
      - name: https
        port: 443
        targetPort: 443
        nodePort: 30443
  target:
    kind: Service
    name: simple-ingress-controller