apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Deployment.yaml
  - Service.yaml
  - ConfigMap.yaml
  - Secret.yaml

labels:
  - pairs:
      app: order-service
      component: microservices

images:
  - name: yahyazakaria123/ecommerce-app-order-service
    newTag: latest

namespace: microservices

replicas:
  - name: order-service
    count: 2