apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: payment-service
  namespace: microservices

resources:
- Deployment.yaml
- Service.yaml
- ConfigMap.yaml
- Secret.yaml

# Use 'labels' instead of deprecated 'commonLabels'
labels:
- pairs:
    app: payment-service
    component: microservices
    version: latest
    tier: business-logic
    service-type: payment-processing

images:
- name: yahyazakaria123/ecommerce-app-payment-service
  newTag: latest

namespace: microservices

replicas:
- name: payment-service
  count: 2
